import { Toaster } from "sonner";
import ConvexClientProvider from "./ConvexClientProvider";
import "./globals.css";
import Provider from "./provider";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SidebarProvider defaultOpen={false}>
          <ConvexClientProvider>
            <Provider>
                {children}
              <Toaster />
            </Provider>
          </ConvexClientProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
